### ISSUE TITLE
sudden multiple incorrect absences recorded for the 05/11 to 08/11

### ISSUE THREAD

**Issue by ngodi** [microverseinc/microverse-issue-tracker#122]
I just noticed absences recorded from the 05/11 to 08/11 today the 11/11. My standup can testify my attendance. Also, these didn't show until today. I have been signing in using my microverse zoom account like usual.

**Comment by ibrolive** [comment]
I have this same issue as well.

**Comment by Keqi** [comment]
The problem has been fixed. We had to restore old meeting time boundaries. Thank you for your report.

**Comment by ngodi** [comment]
ok but I still see the same issue for yesterday 13/11/2019  standup
